#!/bin/bash

rm *.hex *.lst *.err

source=$(echo $1 | sed 's/\.asm//g')
hex=$source.hex

gavrasm $source.asm

if [ ! -f $hex ]
then
    exit
fi

if [ -z "$(lsusb -d 16c0:05dc)" ]
then
    command='echo 1 > /sys/class/leds/F@ST2704N\:green\:inet/brightness ; '
    command+="cat - > /tmp/avrnude.hex ; '
    command+='echo 1 > /sys/class/leds/F@ST2704N\:red\:inet/brightness ; '
    command+='echo 0 > /sys/class/leds/F@ST2704N\:green\:inet/brightness ; '
    command+="avrdude -c usbasp-clone -p $1 -U flash:w:/tmp/avrnude.hex ; "
    command+='echo 0 > /sys/class/leds/F@ST2704N\:red\:inet/brightness ; '
    cat $hex | ssh root@avrnude $command
else
    avrdude -c usbasp-clone -p m324p -U flash:w:$hex
fi
